ruby ../../internal/generate_autoform_v2/generate_view_form.rb  bladder.csv              bladder_and_urethra           >  bladder.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  female_genitalia.csv     internal_genitalia_female     >  female_genitalia.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  large_intestine.csv      large_intestine_and_appendix  >  large_intestine.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  left_adrenal_gland.csv   left_adrenal_gland            >  left_adrenal_gland.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  left_kidneys.csv         left_kidneys_and_ureter       >  left_kidneys.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  liver.csv                liver_and_biiary_system       >  liver.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  male_genetalia.csv       internal_genitalia_male       >  male_genetalia.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  pancreas.csv             pancreas                      >  pancreas.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  paritoneal.csv           peritoneal_cavity             >  paritoneal.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  right_adrenal_gland.csv  right_adrenal_gland           >  right_adrenal_gland.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  right_kidneys.csv        right_kidneys_and_ureter      >  right_kidneys.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  small_intestine.csv      small_intestine               >  small_intestine.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  spleen.csv               spleen                        >  spleen.html.erb
ruby ../../internal/generate_autoform_v2/generate_view_form.rb  stomach.csv              stomach_and_duodenum          >  stomach.html.erb
