# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20170403161824) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"
  enable_extension "uuid-ossp"

  create_table "ancillary_testings", force: :cascade do |t|
    t.string   "microbiology"
    t.string   "viral_culture"
    t.string   "karyotype_requested"
    t.string   "electron_microscopy"
    t.string   "molecular_diagnostic_pathology"
    t.string   "specimens_snap_frozen"
    t.string   "post_mortem_x_rays"
    t.string   "photographs"
    t.string   "organs_for_special_study"
    t.string   "other"
    t.integer  "description_id"
    t.datetime "created_at",                     null: false
    t.datetime "updated_at",                     null: false
    t.string   "microbiology_specify"
    t.string   "viral_culture_specify"
    t.string   "karyotype_requested_specify"
    t.string   "electron_microscopy_specify"
  end

  add_index "ancillary_testings", ["description_id"], name: "index_ancillary_testings_on_description_id", using: :btree

  create_table "block_codes", force: :cascade do |t|
    t.integer  "block_number"
    t.text     "block_description"
    t.integer  "description_id"
    t.datetime "created_at",        null: false
    t.datetime "updated_at",        null: false
  end

  add_index "block_codes", ["description_id"], name: "index_block_codes_on_description_id", using: :btree

  create_table "clinico_pathological_summaries", force: :cascade do |t|
    t.string   "clinpath_summary"
    t.string   "references"
    t.integer  "description_id"
    t.datetime "created_at",       null: false
    t.datetime "updated_at",       null: false
  end

  add_index "clinico_pathological_summaries", ["description_id"], name: "index_clinico_pathological_summaries_on_description_id", using: :btree

  create_table "consultants", force: :cascade do |t|
    t.integer  "description_id"
    t.datetime "created_at",     null: false
    t.datetime "updated_at",     null: false
    t.integer  "user_id"
  end

  add_index "consultants", ["description_id"], name: "index_consultants_on_description_id", using: :btree
  add_index "consultants", ["user_id"], name: "index_consultants_on_user_id", using: :btree

  create_table "descriptions", force: :cascade do |t|
    t.text     "description"
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.string   "case_identifier"
    t.integer  "user_id"
  end

  add_index "descriptions", ["user_id"], name: "index_descriptions_on_user_id", using: :btree

  create_table "externals", force: :cascade do |t|
    t.string   "nutrition"
    t.string   "hydration_including_edema"
    t.string   "facies"
    t.string   "embalmed"
    t.string   "rigor"
    t.string   "livor"
    t.string   "cyanosis"
    t.string   "icterus"
    t.string   "tubes"
    t.string   "catheters"
    t.string   "needle_marks"
    t.string   "incisions_scars"
    t.string   "rash_excoriation"
    t.string   "petechiae"
    t.string   "ecchymoses"
    t.string   "nevi_angiomas"
    t.string   "configuration_size"
    t.string   "hair_color"
    t.string   "scalp_subcutaneous"
    t.string   "scalp_subgaleal"
    t.string   "calvarium_sutures"
    t.string   "anterior_fontanelle"
    t.string   "head_other"
    t.string   "position"
    t.string   "shape"
    t.string   "canals"
    t.string   "ears_other"
    t.string   "size_shape_position"
    t.string   "lids_periorbital_soft_tissue"
    t.string   "conjunctiva"
    t.string   "sclera_cornea_lens"
    t.string   "iris_color"
    t.string   "pupils"
    t.string   "eyes_removed"
    t.text     "eyes_other"
    t.string   "position_shape"
    t.string   "nares_exudate"
    t.string   "patency_of_choanae"
    t.string   "septum"
    t.text     "nose_other"
    t.string   "lips_mucosa_gums"
    t.string   "tongue"
    t.string   "palate_maxilla_mandible"
    t.integer  "teeth_upper"
    t.integer  "teeth_lower"
    t.string   "tonsils"
    t.string   "salivary_glands"
    t.string   "pharynx"
    t.text     "mouth_other"
    t.string   "neck_configuration"
    t.string   "nodes_masses"
    t.text     "neck_other"
    t.string   "axilla_configuration"
    t.string   "axillary_lymph_nodes"
    t.text     "chest_other"
    t.string   "abdomen_configuration"
    t.string   "umbilicus_abdominal_wall"
    t.string   "size_of_palpable_organs"
    t.string   "masses"
    t.text     "abdomen_other"
    t.string   "hernia"
    t.string   "palpable_lymph_nodes"
    t.text     "inguinal_other"
    t.string   "penis"
    t.string   "penile_length"
    t.string   "scrotum"
    t.string   "bilateral_testes_identified"
    t.string   "testes_size"
    t.string   "testes_position"
    t.string   "labia"
    t.string   "clitoris"
    t.string   "vagina_hymen"
    t.string   "urethral_meatus"
    t.text     "genitalia_other"
    t.string   "spine"
    t.string   "anus"
    t.text     "back_other"
    t.string   "extermities_configuration"
    t.string   "joints"
    t.string   "dermatoglyphics"
    t.text     "extermities_other"
    t.integer  "description_id"
    t.datetime "created_at",                           null: false
    t.datetime "updated_at",                           null: false
    t.string   "development_habitus"
    t.string   "tubes_specify"
    t.string   "catheters_specify"
    t.string   "needle_marks_specify"
    t.string   "incisions_scars_specify"
    t.string   "rash_excoriation_specify"
    t.string   "petechiae_specify"
    t.string   "ecchymoses_specify"
    t.string   "nevi_angiomas_specify"
    t.string   "configuration_size_specify"
    t.string   "scalp_subcutaneous_specify"
    t.string   "scalp_subgaleal_specify"
    t.string   "calvarium_sutures_specify"
    t.string   "shape_specify"
    t.string   "canals_specify"
    t.string   "size_shape_position_specify"
    t.string   "lids_periorbital_soft_tissue_specify"
    t.string   "conjunctiva_specify"
    t.string   "sclera_cornea_lens_specify"
    t.string   "iris_color_specify"
    t.string   "position_shape_specify"
    t.string   "nares_exudate_specify"
    t.string   "septum_specify"
    t.string   "lips_mucosa_gums_specify"
    t.string   "tongue_specify"
    t.string   "palate_maxilla_mandible_specify"
    t.string   "tonsils_specify"
    t.string   "salivary_glands_specify"
    t.string   "pharynx_specify"
    t.string   "neck_configuration_specify"
    t.string   "Nodes_masses_specify"
    t.string   "axilla_configuration_specify"
    t.string   "axillary_lymph_nodes_specify"
    t.string   "abdomen_configuration_specify"
    t.string   "umbilicus_abdominal_wall_specify"
    t.string   "size_of_palpable_organs_specify"
    t.string   "masses_specify"
    t.string   "hernia_specify"
    t.string   "palpable_lymph_nodes_specify"
    t.string   "penile_length_specify"
    t.string   "scrotum_specify"
    t.string   "bilateral_testes_identified_specify"
    t.string   "testes_size_specify"
    t.string   "labia_specify"
    t.string   "clitoris_specify"
    t.string   "vagina_hymen_specify"
    t.string   "urethral_meatus_specify"
    t.string   "spine_specify"
    t.string   "anus_specify"
    t.string   "extermities_configuration_specify"
    t.string   "joints_specify"
    t.string   "dermatoglyphics_specify"
    t.string   "anterior_fontanelle_measurement"
    t.string   "nodes_masses_specify"
    t.float    "birth_weight"
    t.float    "weight_at_autopsy"
    t.float    "crown_heel_length"
    t.float    "crown_rump_length"
    t.float    "head_circumference"
    t.float    "chest_circumference"
    t.float    "abdomen_circumference"
    t.float    "foot_length"
    t.float    "inner_intercanthal_distance"
    t.float    "interpupillary_distance"
    t.float    "outer_intercanthal_distance"
    t.float    "arm_length"
    t.float    "leg_length"
    t.string   "degree_of_maceration"
    t.text     "pupils_specify"
    t.text     "patency_of_choanae_specify"
  end

  add_index "externals", ["description_id"], name: "index_externals_on_description_id", using: :btree

  create_table "final_diagnoses", force: :cascade do |t|
    t.text     "report"
    t.integer  "description_id"
    t.string   "status"
    t.datetime "created_at",     null: false
    t.datetime "updated_at",     null: false
  end

  add_index "final_diagnoses", ["description_id"], name: "index_final_diagnoses_on_description_id", using: :btree

  create_table "internals", force: :cascade do |t|
    t.string   "fat"
    t.string   "hydration"
    t.text     "subcutaneous_other"
    t.string   "peritoneal_serosal_surfaces"
    t.text     "fluid"
    t.integer  "fluid_quantity"
    t.string   "peritoneal_nature_of_fluid"
    t.string   "peritoneal_cavity_organ_relations"
    t.string   "retrroperitoneum"
    t.string   "umbilical_vessels"
    t.string   "no_of_umbilical_arteries"
    t.text     "peritoneal_cavity_other"
    t.string   "pleural_serosal_surfaces"
    t.string   "pneumothorax"
    t.string   "pleural_cavities_amount_of_fluid"
    t.string   "pleural_nature_of_fluid"
    t.string   "pleural_cavity_organ_relations"
    t.string   "diaphragm"
    t.text     "pleural_cavities_other"
    t.string   "mediastinum_position_configuration"
    t.string   "mediastinum_nodes_masses"
    t.string   "pneumomediastinum"
    t.text     "mediastinum_other"
    t.string   "serosal_sarfaces"
    t.string   "pericardial_sac_contents"
    t.string   "pericardial_sac_amount_of_fluid"
    t.string   "heart_position"
    t.string   "epicardium"
    t.string   "heart_shape"
    t.string   "heart_size"
    t.integer  "heart_only_weight"
    t.integer  "combined_heart_and_lungs_weight"
    t.string   "configuration_and_contents"
    t.string   "atrial_situs"
    t.string   "ventricular_situs"
    t.string   "atrial_septum"
    t.string   "ventricular_septum"
    t.string   "endocardium"
    t.string   "myocardium"
    t.integer  "right_ventricular_wall_thickness"
    t.integer  "left_ventricular_wall_thickness"
    t.string   "tricuspid_valve"
    t.integer  "tricuspid_valve_circumference"
    t.string   "pulmonic_valve"
    t.integer  "pulmonic_valave_circumference"
    t.string   "mitral_valve"
    t.integer  "mitral_valve_circumference"
    t.string   "aortic_valve"
    t.integer  "aortic_valve_circumference"
    t.string   "origins_of_aorta_and_pulmonary_artery"
    t.string   "arch_configuartion"
    t.string   "coronary_arteries"
    t.string   "arch_branches"
    t.string   "thoracic_and_abdominal_branches"
    t.string   "intima_and_wall"
    t.string   "pulmonary_arteries"
    t.string   "ductus"
    t.string   "venous_system_anomalies"
    t.string   "venous_system_state_of_distension"
    t.string   "venous_system_contents"
    t.text     "cardiovascular_other"
    t.string   "epiglottis"
    t.string   "foreign_material_in_lumen"
    t.string   "larynx_trachea_configuration_position"
    t.string   "vocal_cords"
    t.string   "tracheastomy"
    t.string   "mucosal_surfaces"
    t.string   "tracheal_rings"
    t.text     "larynx_other"
    t.integer  "right_lungs_weight"
    t.integer  "left_lung_weight"
    t.integer  "bilateral"
    t.integer  "lung_to_body_weight_ratio"
    t.string   "lobar_pattern"
    t.string   "state_of_expansion"
    t.string   "lungs_consistency"
    t.string   "bronchial_tree"
    t.string   "vessels"
    t.string   "parenchyma_color"
    t.string   "congestion"
    t.string   "interstitial_emphysema"
    t.string   "hilar_nodes"
    t.string   "visceral_pleura"
    t.string   "pleural_petechiae"
    t.string   "fixed_by_perfusion"
    t.string   "esophagus_size_position_configuration"
    t.string   "esophagus_mucosa_and_wall"
    t.string   "stomach_size_position_configuration"
    t.string   "stomach_mucosa_and_wall"
    t.text     "stomach_and_duodenum_contents"
    t.string   "ampulla"
    t.string   "small_intestine_size_position_configuration"
    t.string   "small_intestine_rotation"
    t.string   "small_intestine_mucosa_and_wall"
    t.string   "small_intestine_state_of_distension"
    t.text     "small_intestine_contents"
    t.string   "mecekel_diverticulum"
    t.string   "large_intestine_size_position_configuration"
    t.string   "large_intestine_rotation"
    t.string   "large_intestine_mucosa_and_wall"
    t.string   "large_intestine_state_of_distension"
    t.text     "large_intestine_contents"
    t.string   "configuration"
    t.integer  "liver_weight"
    t.string   "liver_size_shape"
    t.string   "liver_and_billiary_system_external_surface"
    t.string   "cut_surface"
    t.string   "gallbladder"
    t.string   "bile_ducts"
    t.string   "bile"
    t.string   "stones"
    t.string   "vessels_portal_vein_hepatic_artery"
    t.integer  "pancreas_weight"
    t.string   "size_configuration"
    t.string   "pancreas_parenchyma_or_cut_surface"
    t.string   "ducts"
    t.string   "genitourinary_anomalies"
    t.integer  "right_kidnes_weight"
    t.string   "right_kidney_configuration_position"
    t.string   "right_kidney_external_surface"
    t.string   "right_kidney_parenchyma_or_cut_surface"
    t.integer  "right_kidney_cortical_thickness"
    t.integer  "right_kidney_medulla_depth"
    t.string   "right_kidney_pelves_and_calyces"
    t.string   "right_kidney_peripelvic_fat_and_lymph_nodes"
    t.string   "right_kidney_renal_vessels"
    t.string   "right_kidney_ureter"
    t.integer  "left_kidney_weight"
    t.string   "left_kidney_configuration_position"
    t.string   "left_kidney_external_surface"
    t.string   "left_kidney_parenchyma_or_cut_surface"
    t.integer  "left_kidney_cortical_thickness"
    t.integer  "left_kidney_medulla_depth"
    t.string   "left_kidney_pelves_and_calyces"
    t.string   "left_kideny_peripelvic_fat_and_lymph_nodes"
    t.string   "left_panel_renal_vessels"
    t.string   "left_kidney_ureter"
    t.string   "size_and_configuration"
    t.string   "wall_and_mucosa"
    t.string   "perivesical_tissue"
    t.string   "bladder_contents"
    t.string   "urethra"
    t.string   "prostate"
    t.string   "epididymis"
    t.string   "testes"
    t.text     "male_genetalia_other"
    t.string   "vagina"
    t.string   "uterus"
    t.string   "right_fallopian_tubes"
    t.string   "right_ovary"
    t.string   "left_fallopian_tube"
    t.string   "left_ovary"
    t.text     "female_genetalia_other"
    t.integer  "right_adrenal_gland_weight"
    t.string   "right_adrenal_pos_config_shape"
    t.string   "right_adrenal_gland_external_surface"
    t.string   "right_adrenal_gland_parenchyma_or_cut_surface"
    t.string   "right_adrenal_cortex"
    t.string   "right_adrenal_fetal_cortex"
    t.string   "right_adrenal_medulla"
    t.text     "right_adrenal_other"
    t.integer  "left_adrenal_gland_weight"
    t.string   "left_adrenal_pos_config_shape"
    t.string   "left_adrenal_gland_external_surface"
    t.string   "left_adrenal_gland_parenchyma_or_cut_surface"
    t.string   "left_adrenal_cortex"
    t.string   "left_adrenal_fetal_cortex"
    t.string   "left_adrenal_medulla"
    t.text     "left_adrenal_other"
    t.integer  "thyroid_weight"
    t.string   "thyroid_pos_config_shape"
    t.string   "thyroid_external_surface"
    t.string   "thyroid_parenchyma_or_cut_surface"
    t.text     "thyroid_other"
    t.integer  "pituitary_weight"
    t.string   "pituitary_pos_config_shape"
    t.string   "pituitary_external_surface"
    t.string   "pituitary_parenchyma_or_cut_surface"
    t.string   "parathyroid_gland"
    t.integer  "weight"
    t.string   "thymus_pos_config_shape"
    t.string   "petechiae_on_external_surface"
    t.string   "thymus_parenchyma_or_cut_surface"
    t.text     "thymus_other"
    t.integer  "spleen_weight"
    t.string   "spleen_shape_position_configuration"
    t.string   "capsular_surface"
    t.string   "spleen_consistency"
    t.string   "spleen_parenchyma_or_cut_surface"
    t.string   "accessory_spleens"
    t.text     "spleen_other"
    t.text     "cervical"
    t.text     "axillary"
    t.text     "mediastinal"
    t.text     "hilar"
    t.text     "celiac_peripancreatic"
    t.text     "mesenteric"
    t.text     "periaortic"
    t.text     "iliac"
    t.text     "inguinal"
    t.text     "lymph_nodes_other"
    t.string   "hardness"
    t.string   "bone_anomalies"
    t.string   "marrow"
    t.text     "bones_other"
    t.string   "skeletal_muscle_color_consistency"
    t.string   "skeletal_muscle_size"
    t.text     "skeletal_muscle_other"
    t.string   "bones"
    t.string   "sutures_fontanelles"
    t.string   "skull_base"
    t.string   "sella"
    t.string   "petrous_pyramids_opened_and_cultured"
    t.string   "ears_removed"
    t.integer  "foramen_magnum_antero_posterior_dimension"
    t.integer  "foramen_magnum_antero_lateral_dimension"
    t.text     "cranium_other"
    t.string   "dura_falx_tentorium"
    t.string   "subdural_epidural"
    t.string   "venous_sinuses"
    t.text     "sinuses_other"
    t.integer  "brain_weight"
    t.string   "configuration_lobar_pattern"
    t.string   "brain_consistency"
    t.string   "pachymeninges"
    t.string   "blood_vessels"
    t.string   "cranial_nerves"
    t.string   "kernicterus"
    t.string   "extradural_space"
    t.string   "meninges"
    t.string   "cord_proper"
    t.string   "peripheral_nervous_system"
    t.string   "peritoneal_serosal_surfaces_specify"
    t.string   "peritoneal_cavity_organ_relations_specify"
    t.string   "retrroperitoneum_specify"
    t.string   "umbilical_vessels_specify"
    t.string   "pleural_serosal_surfaces_specify"
    t.string   "pleural_cavity_organ_relations_specify"
    t.string   "diaphragm_specify"
    t.string   "mediastinum_position_configuration_specify"
    t.string   "mediastinum_nodes_masses_specify"
    t.string   "serosal_sarfaces_specify"
    t.string   "heart_position_specify"
    t.string   "epicardium_specify"
    t.string   "heart_shape_specify"
    t.string   "heart_size_specify"
    t.string   "configuration_and_contents_specify"
    t.string   "atrial_situs_specify"
    t.string   "ventricular_situs_specify"
    t.string   "ventricular_septum_specify"
    t.string   "endocardium_specify"
    t.string   "myocardium_specify"
    t.string   "tricuspid_valve_specify"
    t.string   "pulmonic_valve_specify"
    t.string   "mitral_valve_specify"
    t.string   "aortic_valve_specify"
    t.string   "origins_of_aorta_and_pulmonary_artery_specify"
    t.string   "arch_configuartion_specify"
    t.string   "coronary_arteries_specify"
    t.string   "arch_branches_specify"
    t.string   "thoracic_and_abdominal_branches_specify"
    t.string   "intima_and_wall_specify"
    t.string   "pulmonary_arteries_specify"
    t.string   "venous_system_state_of_distension_specify"
    t.string   "epiglottis_specify"
    t.string   "larynx_trachea_configuration_position_specify"
    t.string   "vocal_cords_specify"
    t.string   "mucosal_surfaces_specify"
    t.string   "lobar_pattern_specify"
    t.string   "state_of_expansion_specify"
    t.string   "lungs_consistency_specify"
    t.string   "bronchial_tree_specify"
    t.string   "vessels_specify"
    t.string   "parenchyma_color_specify"
    t.string   "hilar_nodes_specify"
    t.string   "visceral_pleura_specify"
    t.string   "esophagus_size_position_configuration_specify"
    t.string   "esophagus_mucosa_and_wall_specify"
    t.string   "stomach_size_position_configuration_specify"
    t.string   "stomach_mucosa_and_wall_specify"
    t.string   "ampulla_specify"
    t.string   "small_intestine_size_position_configuration_specify"
    t.string   "small_intestine_rotation_specify"
    t.string   "small_intestine_mucosa_and_wall_specify"
    t.string   "small_intestine_state_of_distension_specify"
    t.string   "large_intestine_size_position_configuration_specify"
    t.string   "large_intestine_rotation_specify"
    t.string   "large_intestine_mucosa_and_wall_specify"
    t.string   "large_intestine_state_of_distension_specify"
    t.string   "configuration_specify"
    t.string   "liver_size_shape_specify"
    t.string   "liver_and_billiary_system_external_surface_specify"
    t.string   "cut_surface_specify"
    t.string   "gallbladder_specify"
    t.string   "bile_ducts_specify"
    t.string   "vessels_portal_vein_hepatic_artery_specify"
    t.string   "size_configuration_specify"
    t.string   "pancreas_parenchyma_or_cut_surface_specify"
    t.string   "ducts_specify"
    t.string   "right_kidney_configuration_position_specify"
    t.string   "right_kidney_external_surface_specify"
    t.string   "right_kidney_parenchyma_or_cut_surface_specify"
    t.string   "right_kidney_pelves_and_calyces_specify"
    t.string   "right_kidney_peripelvic_fat_and_lymph_nodes_specify"
    t.string   "right_kidney_renal_vessels_specify"
    t.string   "right_kidney_ureter_specify"
    t.string   "left_kidney_configuration_position_specify"
    t.string   "left_kidney_external_surface_specify"
    t.string   "left_kidney_parenchyma_or_cut_surface_specify"
    t.string   "left_kidney_pelves_and_calyces_specify"
    t.string   "left_kideny_peripelvic_fat_and_lymph_nodes_specify"
    t.string   "left_panel_renal_vessels_specify"
    t.string   "left_kidney_ureter_specify"
    t.string   "size_and_configuration_specify"
    t.string   "wall_and_mucosa_specify"
    t.string   "perivesical_tissue_specify"
    t.string   "urethra_specify"
    t.string   "prostate_specify"
    t.string   "epididymis_specify"
    t.string   "testes_specify"
    t.string   "vagina_specify"
    t.string   "uterus_specify"
    t.string   "right_fallopian_tubes_specify"
    t.string   "right_ovary_specify"
    t.string   "left_fallopian_tube_specify"
    t.string   "left_ovary_specify"
    t.string   "right_adrenal_pos_config_shape_specify"
    t.string   "right_adrenal_gland_external_surface_specify"
    t.string   "right_adrenal_gland_parenchyma_or_cut_surface_specify"
    t.string   "right_adrenal_cortex_specify"
    t.string   "right_adrenal_fetal_cortex_specify"
    t.string   "right_adrenal_medulla_specify"
    t.string   "left_adrenal_pos_config_shape_specify"
    t.string   "left_adrenal_gland_external_surface_specify"
    t.string   "left_adrenal_gland_parenchyma_or_cut_surface_specify"
    t.string   "left_adrenal_cortex_specify"
    t.string   "left_adrenal_fetal_cortex_specify"
    t.string   "left_adrenal_medulla_specify"
    t.string   "thyroid_pos_config_shape_specify"
    t.string   "thyroid_external_surface_specify"
    t.string   "thyroid_parenchyma_or_cut_surface_specify"
    t.string   "pituitary_pos_config_shape_specify"
    t.string   "pituitary_external_surface_specify"
    t.string   "pituitary_parenchyma_or_cut_surface_specify"
    t.string   "thymus_pos_config_shape_specify"
    t.string   "thymus_parenchyma_or_cut_surface_specify"
    t.string   "spleen_shape_position_configuration_specify"
    t.string   "capsular_surface_specify"
    t.string   "spleen_consistency_specify"
    t.string   "spleen_parenchyma_or_cut_surface_specify"
    t.string   "hardness_specify"
    t.string   "bone_anomalies_specify"
    t.string   "marrow_specify"
    t.string   "skeletal_muscle_color_consistency_specify"
    t.string   "skeletal_muscle_size_specify"
    t.string   "bones_specify"
    t.string   "sutures_fontanelles_specify"
    t.string   "skull_base_specify"
    t.string   "sella_specify"
    t.string   "dura_falx_tentorium_specify"
    t.string   "subdural_epidural_specify"
    t.string   "venous_sinuses_specify"
    t.string   "configuration_lobar_pattern_specify"
    t.string   "brain_consistency_specify"
    t.string   "pachymeninges_specify"
    t.string   "blood_vessels_specify"
    t.string   "cranial_nerves_specify"
    t.string   "kernicterus_specify"
    t.string   "extradural_space_specify"
    t.string   "meninges_specify"
    t.string   "cord_proper_specify"
    t.string   "pleural_cavities_amount_of_fluid_specify"
    t.string   "pericardial_sac_amount_of_fluid_specify"
    t.string   "atrial_septum_specify"
    t.string   "ductus_specify"
    t.string   "peritoneal_nature_of_fluid_specify"
    t.string   "pleural_nature_of_fluid_specify"
    t.string   "pericardial_sac_contents_specify"
    t.string   "bile_specify"
    t.string   "venous_system_anomalies_specify"
    t.string   "stones_specify"
    t.string   "bladder_contents_specify"
    t.integer  "accessory_spleens_number"
    t.integer  "mecekel_diverticulum_size"
    t.string   "pneumothorax_specify"
    t.string   "foreign_material_in_lumen_specify"
    t.string   "fixed_by_perfusion_specify"
    t.string   "genitourinary_anomalies_specify"
    t.string   "petrous_pyramids_opened_and_cultured_specify"
    t.string   "ears_removed_specify"
    t.integer  "description_id"
    t.datetime "created_at",                                            null: false
    t.datetime "updated_at",                                            null: false
    t.boolean  "subcutaneous_normal"
    t.boolean  "bones_normal"
    t.boolean  "skeletal_muscle_normal"
    t.string   "skeletal_muscle_consistency"
    t.boolean  "lymphnodes_normal"
    t.boolean  "venous_system_normal"
    t.text     "venous_system_other"
    t.boolean  "arterial_system_normal"
    t.string   "arterial_system_state_of_distension"
    t.string   "arterial_system_contents"
    t.string   "arterial_system_anomalies"
    t.text     "arterial_system_other"
    t.boolean  "lymphatic_system_normal"
    t.string   "lymphatic_system_state_of_distension"
    t.string   "lymphatic_system_contents"
    t.string   "lymphatic_system_anomalies"
    t.text     "lymphatic_system_other"
    t.string   "skeletal_muscle_color"
    t.text     "skeletal_muscle_color_specify"
    t.text     "skeletal_muscle_consistency_specify"
    t.text     "cervical_specify"
    t.text     "axillary_specify"
    t.text     "mediastinal_specify"
    t.text     "hilar_specify"
    t.text     "celiac_peripancreatic_specify"
    t.text     "mesenteric_specify"
    t.text     "periaortic_specify"
    t.text     "iliac_specify"
    t.text     "inguinal_specify"
    t.string   "arterial_system_state_of_distension_specify"
    t.string   "arterial_system_anomalies_specify"
    t.string   "lymphatic_system_state_of_distension_specify"
    t.text     "lymphatic_system_anomalies_specify"
    t.text     "peripheral_nervous_system_specify"
    t.text     "subcutaneous_galea_specify"
    t.string   "subcutaneous_galea"
    t.string   "periosteum"
    t.text     "periosteum_specify"
    t.boolean  "scalp_and_cranium_normal"
    t.boolean  "pituitary_normal"
    t.text     "pituitary_other"
    t.boolean  "dura_and_venous_sinuses_normal"
    t.string   "epidural_space"
    t.string   "epidural_space_specify"
    t.boolean  "brain_preliminary_examination_normal"
    t.text     "brain_other"
    t.boolean  "spinal_cord_normal"
    t.boolean  "larynx_and_trachea_normal"
    t.boolean  "pleural_cavities_normal"
    t.boolean  "mediastinum_normal"
    t.boolean  "lungs_normal"
    t.boolean  "diaphragm_normal"
    t.boolean  "thymus_normal"
    t.boolean  "pericardial_sac_normal"
    t.boolean  "thyroidr_parathyroid_normal"
    t.boolean  "esophagus_normal"
    t.boolean  "heart_normal"
    t.boolean  "chambers_and_septae_normal"
    t.boolean  "valves_normal"
    t.boolean  "vessels_and_ducts_normal"
    t.string   "diaphragm_position_configuration"
    t.text     "diaphragm_position_configuration_specify"
    t.string   "diphragm_defect"
    t.text     "diaphragm_other"
    t.boolean  "thyroid_parathyroid_normal"
    t.text     "parathyroid_gland_specify"
    t.text     "esophagus_other"
    t.string   "heart_configuration"
    t.text     "heart_configuration_specify"
    t.string   "heart_content"
    t.string   "heart_content_specify"
    t.string   "thoracic_branches"
    t.text     "thoracic_branches_specify"
    t.string   "superior_vena_cava"
    t.text     "superior_vena_cava_specify"
    t.string   "inferior_vena_cava"
    t.text     "inferior_vena_cava_specify"
    t.string   "pulmonary_veins"
    t.text     "pulmonary_veins_specify"
    t.boolean  "peritoneal_cavity_normal"
    t.boolean  "stomach_and_duodenum_normal"
    t.boolean  "small_intestine_normal"
    t.boolean  "large_instestine_normal"
    t.boolean  "liver_and_biliary_system_normal"
    t.boolean  "pancreas_normal"
    t.boolean  "right_adrenal_gland_normal"
    t.boolean  "left_adrenal_gland_normal"
    t.boolean  "spleen_normal"
    t.boolean  "right_kidney_and_ureter_normal"
    t.boolean  "left_kidney_and_ureter_normal"
    t.boolean  "bladder_and_urethra_normal"
    t.boolean  "internal_genitalia_male_normal"
    t.boolean  "internal_genitalia_female_normal"
    t.boolean  "stomach_and_duodenum_other"
    t.string   "meckel_diverticulum"
    t.text     "meckel_diverticulum_specify"
    t.string   "small_intestine_mesentery"
    t.string   "small_intestine_mesentery_specify"
    t.string   "small_intestine_other"
    t.string   "large_intestine_mesentery"
    t.text     "large_intestine_mesentery_specify"
    t.text     "large_intestine_other"
    t.string   "hilar_vessels_portal_vein_hepatic_artery"
    t.string   "hilar_vessels_portal_vein_hepatic_artery_specify"
    t.text     "liver_and_biiary_system_other"
    t.string   "pancreas_size_configuration"
    t.text     "pancreas_size_configuration_specify"
    t.string   "pancreas_external_surface"
    t.text     "pancreas_external_surface_specify"
    t.text     "pancreas_other"
    t.string   "spleen_cut_surface"
    t.text     "spleen_cut_surface_specify"
    t.text     "accessory_spleens_specify"
    t.float    "right_kidney_weight"
    t.string   "right_kidney_cut_surface"
    t.text     "right_kidney_cut_surface_specify"
    t.string   "left_kidney_cut_surface"
    t.text     "left_kidney_cut_surface_specify"
    t.text     "right_kidney_other"
    t.text     "left_kidney_other"
    t.text     "bladder_and_urethra_other"
    t.text     "block_code_composite"
    t.text     "arterial_system_md"
    t.text     "bone_md"
    t.text     "lymphatic_system_md"
    t.text     "peripheral_nervous_system_md"
    t.text     "skeletal_muscle_md"
    t.text     "subcutaneous_md"
    t.text     "venous_system_md"
    t.text     "lymph_nodes_md"
    t.text     "brain_md"
    t.text     "cranium_md"
    t.text     "dura_and_venous_sinuses_md"
    t.text     "pituitary_md"
    t.text     "spinal_cord_md"
    t.text     "chambers_and_septae_md"
    t.text     "diaphragm_md"
    t.text     "esophagus_md"
    t.text     "heart_md"
    t.text     "larynx_md"
    t.text     "lungs_md"
    t.text     "mediastinum_md"
    t.text     "pericardial_sac_md"
    t.text     "pleural_cavities_md"
    t.text     "thymus_md"
    t.text     "thyroid_pt_md"
    t.text     "valves_md"
    t.text     "vessels_and_ducts_md"
    t.text     "bladder_and_urethra_md"
    t.text     "female_genetalia_md"
    t.text     "large_intestine_md"
    t.text     "left_adrenal_gland_md"
    t.text     "left_kidney_ureter_md"
    t.text     "liver_and_biliary_system_md"
    t.text     "male_genetalia_md"
    t.text     "pancreas_md"
    t.text     "peritoneal_cavity_md"
    t.text     "right_adrenal_gland_md"
    t.text     "right_kidney_and_ureter_md"
    t.text     "small_intesting_md"
    t.text     "spleen_md"
    t.text     "stomach_and_duodenum_md"
  end

  add_index "internals", ["description_id"], name: "index_internals_on_description_id", using: :btree

  create_table "mother_data", force: :cascade do |t|
    t.integer  "mother_age"
    t.integer  "gestational_age"
    t.string   "prenatal_care"
    t.integer  "gravida"
    t.integer  "para"
    t.integer  "abortus"
    t.integer  "term"
    t.integer  "pre_pregnancy_weight"
    t.integer  "delivery_weight"
    t.string   "blood_type"
    t.string   "antibody_screen"
    t.string   "rpr"
    t.string   "hepatitis_b"
    t.string   "rubella"
    t.string   "HIV"
    t.string   "diabetes"
    t.string   "GBS"
    t.string   "amniocentesis"
    t.text     "previous_pregnancy_summary"
    t.text     "present_pregnancy_summary"
    t.text     "ultrasound_finding"
    t.integer  "birth_weight"
    t.string   "maceration_degree"
    t.string   "gross_appearance"
    t.string   "placenta_available_for_examination"
    t.string   "amniotic_fluid"
    t.text     "mother_medical_history"
    t.integer  "description_id"
    t.datetime "created_at",                                      null: false
    t.datetime "updated_at",                                      null: false
    t.string   "living"
    t.float    "height"
    t.string   "height_unit"
    t.float    "pre_pregnancy_bmi"
    t.float    "delivery_bmi"
    t.string   "pre_pregnancy_weight_unit"
    t.string   "delivery_weight_unit"
    t.string   "amniocentesis_explain"
    t.string   "feto_placental_findings_at_the_time_of_delivery"
    t.string   "birth_weight_unit"
    t.string   "placenta"
    t.string   "placenta_specify"
    t.string   "amniotic_fluid_specify"
    t.string   "type_of_delivery"
    t.string   "type_of_delivery_specify"
  end

  add_index "mother_data", ["description_id"], name: "index_mother_data_on_description_id", using: :btree

  create_table "neuroblastomas", force: :cascade do |t|
    t.string   "specimen"
    t.string   "specimen_specify"
    t.string   "procedure"
    t.string   "procedure_specify"
    t.float    "specimen_size_greatest_dimension"
    t.float    "specimen_size_additional_dimension_1"
    t.float    "specimen_size_additional_dimension_2"
    t.float    "specimen_weight"
    t.string   "specimen_laterality"
    t.string   "specimen_laterality_specify"
    t.float    "tumor_size_gretest_dimenstion"
    t.float    "tumor_size_additional_dimenstions_1"
    t.float    "tumor_size_additional_dimenstions_2"
    t.string   "tumor_size_cant_be_assessed"
    t.float    "tumor_weight"
    t.float    "tumor_weight_cant_be_assessed"
    t.string   "age"
    t.string   "histological_type"
    t.integer  "histological_type_nodular_subtype_specify"
    t.string   "degree_of_differentiation"
    t.string   "mitotic_karyorrhectic_index"
    t.string   "tumor_calcification"
    t.string   "treatment_history"
    t.string   "international_classification"
    t.string   "margins"
    t.string   "margins_specify"
    t.string   "lymph_vascular_invasion"
    t.string   "primary_tumor"
    t.string   "regional_lymph_nodes"
    t.string   "regional_lymph_nodes_sites"
    t.integer  "regional_lymph_nodes_examined_number"
    t.integer  "regional_lymph_nodes_involved_number"
    t.string   "distant_metastasis"
    t.string   "distant_metastasis_sites"
    t.string   "inss_stage"
    t.string   "mycn_amplification_status"
    t.string   "other"
    t.string   "comments"
    t.datetime "created_at",                                null: false
    t.datetime "updated_at",                                null: false
    t.string   "report_identifier"
  end

  create_table "organ_weights", force: :cascade do |t|
    t.integer  "brain_expected"
    t.integer  "brain_observed"
    t.integer  "heart_expected"
    t.integer  "heart_observed"
    t.integer  "liver_expected"
    t.integer  "liver_observed"
    t.integer  "lt_adrenal_expected"
    t.integer  "lt_adrenal_observed"
    t.integer  "lt_kidney_expected"
    t.integer  "lt_kidney_observed"
    t.integer  "lt_lung_expected"
    t.integer  "lt_lung_observed"
    t.integer  "rt_adrenal_expected"
    t.integer  "rt_adrenal_observed"
    t.integer  "rt_kidney_expected"
    t.integer  "rt_kidney_observed"
    t.integer  "rt_lung_expected"
    t.integer  "rt_lung_observed"
    t.integer  "spleen_expected"
    t.integer  "spleen_observed"
    t.integer  "thymus_expected"
    t.integer  "thymus_observed"
    t.integer  "patient_id"
    t.datetime "created_at",          null: false
    t.datetime "updated_at",          null: false
  end

  add_index "organ_weights", ["patient_id"], name: "index_organ_weights_on_patient_id", using: :btree

  create_table "patients", force: :cascade do |t|
    t.string   "name"
    t.string   "dob"
    t.string   "case"
    t.string   "hospital"
    t.integer  "age"
    t.string   "date_admission"
    t.string   "race"
    t.string   "sex"
    t.string   "pathologist"
    t.string   "physician"
    t.string   "attendant"
    t.string   "date_autopsy"
    t.string   "time_of_autopsy"
    t.string   "restrictions"
    t.string   "prosector"
    t.datetime "created_at",        null: false
    t.datetime "updated_at",        null: false
    t.integer  "description_id_id"
    t.integer  "description_id"
    t.string   "time_of_birth"
    t.integer  "age_day_week"
  end

  create_table "placenta", force: :cascade do |t|
    t.float    "weight"
    t.float    "placental_weight_ratio"
    t.float    "total_length"
    t.string   "vessels"
    t.string   "umbillical_cord_normal"
    t.string   "normal_no_funisitis"
    t.string   "normal_no_acute_vasculitis"
    t.string   "umbillical_cord_normal_no_other"
    t.string   "fetal_memberanes_normal"
    t.string   "normal_no_acute_chorioamnionitis"
    t.string   "normal_no_pigmented_macrophages"
    t.string   "fetal_membranes_normal_no_other"
    t.string   "chorionic_plate_and_stem_vessels_normal"
    t.string   "normal_no_thrombosis"
    t.string   "normal_no_hemorrhagic_endovasculosis"
    t.string   "normal_no_cushion_lesions_with_or_without_fibrin"
    t.string   "chorionic_plate_and_stem_vessels_normal_no_other"
    t.string   "maturation_appropriate_for_gestational_age"
    t.string   "maturation_no_specify"
    t.string   "chorionic_villi_and_intervillous_space_normal"
    t.string   "chorionic_villi_abnormal_chronic_lymphohistiocytic_villitis"
    t.string   "chorionic_villi_abnormal_acute_intervillositis"
    t.string   "chorionic_villi_abnormal_avascular_villi"
    t.string   "chorionic_villi_abnormal_other"
    t.string   "basal_plate_normal"
    t.string   "normal_no_maternal_vessels_normal"
    t.string   "normal_no_decidua_basalis_normal"
    t.string   "normal_no_basalplate_other"
    t.string   "normal_no_maternal_vessels_normal_specify"
    t.string   "normal_no_decidua_basalis_normal_specify"
    t.integer  "description_id"
    t.datetime "created_at",                                                  null: false
    t.datetime "updated_at",                                                  null: false
  end

  add_index "placenta", ["description_id"], name: "index_placenta_on_description_id", using: :btree

  create_table "provisional_diagnoses", force: :cascade do |t|
    t.text     "report"
    t.integer  "description_id"
    t.datetime "created_at",     null: false
    t.datetime "updated_at",     null: false
    t.string   "status"
  end

  add_index "provisional_diagnoses", ["description_id"], name: "index_provisional_diagnoses_on_description_id", using: :btree

  create_table "question_answers", force: :cascade do |t|
    t.string   "major_clinical_diagnosis"
    t.string   "major_pathologic_diagnosis"
    t.string   "clinical_cause_of_death"
    t.string   "pathological_cause_of_death"
    t.string   "discover_a_discrepancy_between_clinical_and_pathologic_diagnosi"
    t.string   "establish_an_unexpected_additional_diagnosis"
    t.string   "confirm_the_major_clinical_diagnosis"
    t.string   "information_relevant_to_genetic_counselling"
    t.string   "information_relevant_to_treatment_effect"
    t.string   "information_on_diagnostic_procedures"
    t.string   "information_relevant_to_previous_lab_or_anatomic_pathology_data"
    t.string   "are_all_parts_of_the_report_complete"
    t.string   "are_the_descriptions_clear"
    t.string   "are_all_gross_abnormalities_confirmed_microscopically"
    t.string   "are_all_appropriate_special_studies_done_and_reported"
    t.string   "diagnoses_justified_on_anatomic_evidence_scroll_down_menu_sayin"
    t.string   "diagnoses_complete"
    t.string   "diagnosis_organized_and_sequenced_by_pathogenetic_significance"
    t.string   "transcriptional_or_typographical_errors"
    t.string   "clinically_relevant_postmortem_findings_addressed_in_cpc"
    t.string   "comments_and_recommendations"
    t.string   "reviewed_by"
    t.string   "date"
    t.integer  "description_id"
    t.string   "are_all_appropriate_special_studies_done_and_reported_specify"
    t.datetime "created_at",                                                      null: false
    t.datetime "updated_at",                                                      null: false
  end

  add_index "question_answers", ["description_id"], name: "index_question_answers_on_description_id", using: :btree

  create_table "special_reports", force: :cascade do |t|
    t.string   "title"
    t.text     "final_diagnosis"
    t.text     "gross_description"
    t.string   "blockcode"
    t.text     "microscopic_description"
    t.string   "assign"
    t.string   "lock"
    t.integer  "description_id"
    t.datetime "created_at",              null: false
    t.datetime "updated_at",              null: false
  end

  add_index "special_reports", ["description_id"], name: "index_special_reports_on_description_id", using: :btree

  create_table "users", force: :cascade do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet     "current_sign_in_ip"
    t.inet     "last_sign_in_ip"
    t.datetime "created_at",                          null: false
    t.datetime "updated_at",                          null: false
    t.boolean  "admin"
    t.boolean  "secretary"
    t.boolean  "physician"
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true, using: :btree

  add_foreign_key "ancillary_testings", "descriptions"
  add_foreign_key "clinico_pathological_summaries", "descriptions"
  add_foreign_key "consultants", "descriptions"
  add_foreign_key "consultants", "users"
  add_foreign_key "descriptions", "users"
  add_foreign_key "externals", "descriptions"
  add_foreign_key "final_diagnoses", "descriptions"
  add_foreign_key "internals", "descriptions"
  add_foreign_key "mother_data", "descriptions"
  add_foreign_key "organ_weights", "patients"
  add_foreign_key "placenta", "descriptions"
  add_foreign_key "provisional_diagnoses", "descriptions"
  add_foreign_key "question_answers", "descriptions"
  add_foreign_key "special_reports", "descriptions"
end
