class CreateInternals < ActiveRecord::Migration
  def change
    create_table :internals do |t|
      t.string :fat
      t.string :hydration
      t.text :subcutaneous_other
      t.string :peritoneal_serosal_surfaces
      t.text :fluid
      t.integer :fluid_quantity
      t.string :peritoneal_nature_of_fluid
      t.string :peritoneal_cavity_organ_relations
      t.string :retrroperitoneum
      t.string :umbilical_vessels
      t.string :no_of_umbilical_arteries
      t.text :peritoneal_cavity_other
      t.string :pleural_serosal_surfaces
      t.string :pneumothorax
      t.string :pleural_cavities_amount_of_fluid
      t.string :pleural_nature_of_fluid
      t.string :pleural_cavity_organ_relations
      t.string :diaphragm
      t.text :pleural_cavities_other
      t.string :mediastinum_position_configuration
      t.string :mediastinum_nodes_masses
      t.string :pneumomediastinum
      t.text :mediastinum_other
      t.string :serosal_sarfaces
      t.string :pericardial_sac_contents
      t.string :pericardial_sac_amount_of_fluid
      t.string :heart_position
      t.string :epicardium
      t.string :heart_shape
      t.string :heart_size
      t.integer :heart_only_weight
      t.integer :combined_heart_and_lungs_weight
      t.string :configuration_and_contents
      t.string :atrial_situs
      t.string :ventricular_situs
      t.string :atrial_septum
      t.string :ventricular_septum
      t.string :endocardium
      t.string :myocardium
      t.integer :right_ventricular_wall_thickness
      t.integer :left_ventricular_wall_thickness
      t.string :tricuspid_valve
      t.integer :tricuspid_valve_circumference
      t.string :pulmonic_valve
      t.integer :pulmonic_valave_circumference
      t.string :mitral_valve
      t.integer :mitral_valve_circumference
      t.string :aortic_valve
      t.integer :aortic_valve_circumference
      t.string :origins_of_aorta_and_pulmonary_artery
      t.string :arch_configuartion
      t.string :coronary_arteries
      t.string :arch_branches
      t.string :thoracic_and_abdominal_branches
      t.string :intima_and_wall
      t.string :pulmonary_arteries
      t.string :ductus
      t.string :venous_system_anomalies
      t.string :venous_system_state_of_distension
      t.string :venous_system_contents
      t.text :cardiovascular_other
      t.string :epiglottis
      t.string :foreign_material_in_lumen
      t.string :larynx_trachea_configuration_position
      t.string :vocal_cords
      t.string :tracheastomy
      t.string :mucosal_surfaces
      t.string :tracheal_rings
      t.text :larynx_other
      t.integer :right_lungs_weight
      t.integer :left_lung_weight
      t.integer :bilateral
      t.integer :combined_heart_and_lungs_weight
      t.integer :lung_to_body_weight_ratio
      t.string :lobar_pattern
      t.string :state_of_expansion
      t.string :lungs_consistency
      t.string :bronchial_tree
      t.string :vessels
      t.string :parenchyma_color
      t.string :congestion
      t.string :interstitial_emphysema
      t.string :hilar_nodes
      t.string :visceral_pleura
      t.string :pleural_petechiae
      t.string :fixed_by_perfusion
      t.string :esophagus_size_position_configuration
      t.string :esophagus_mucosa_and_wall
      t.string :stomach_size_position_configuration
      t.string :stomach_mucosa_and_wall
      t.text :stomach_and_duodenum_contents
      t.string :ampulla
      t.string :small_intestine_size_position_configuration
      t.string :small_intestine_rotation
      t.string :small_intestine_mucosa_and_wall
      t.string :small_intestine_state_of_distension
      t.text :small_intestine_contents
      t.string :mecekel_diverticulum
      t.string :large_intestine_size_position_configuration
      t.string :large_intestine_rotation
      t.string :large_intestine_mucosa_and_wall
      t.string :large_intestine_state_of_distension
      t.text :large_intestine_contents
      t.string :configuration
      t.integer :liver_weight
      t.string :liver_size_shape
      t.string :liver_and_billiary_system_external_surface
      t.string :cut_surface
      t.string :gallbladder
      t.string :bile_ducts
      t.string :bile
      t.string :stones
      t.string :vessels_portal_vein_hepatic_artery
      t.integer :pancreas_weight
      t.string :size_configuration
      t.string :pancreas_parenchyma_or_cut_surface
      t.string :ducts
      t.string :genitourinary_anomalies
      t.integer :right_kidnes_weight
      t.string :right_kidney_configuration_position
      t.string :right_kidney_external_surface
      t.string :right_kidney_parenchyma_or_cut_surface
      t.integer :right_kidney_cortical_thickness
      t.integer :right_kidney_medulla_depth
      t.string :right_kidney_pelves_and_calyces
      t.string :right_kidney_peripelvic_fat_and_lymph_nodes
      t.string :right_kidney_renal_vessels
      t.string :right_kidney_ureter
      t.integer :left_kidney_weight
      t.string :left_kidney_configuration_position
      t.string :left_kidney_external_surface
      t.string :left_kidney_parenchyma_or_cut_surface
      t.integer :left_kidney_cortical_thickness
      t.integer :left_kidney_medulla_depth
      t.string :left_kidney_pelves_and_calyces
      t.string :left_kideny_peripelvic_fat_and_lymph_nodes
      t.string :left_panel_renal_vessels
      t.string :left_kidney_ureter
      t.string :size_and_configuration
      t.string :wall_and_mucosa
      t.string :perivesical_tissue
      t.string :bladder_contents
      t.string :urethra
      t.string :prostate
      t.string :epididymis
      t.string :testes
      t.text :male_genetalia_other
      t.string :vagina
      t.string :uterus
      t.string :right_fallopian_tubes
      t.string :right_ovary
      t.string :left_fallopian_tube
      t.string :left_ovary
      t.text :female_genetalia_other
      t.integer :right_adrenal_gland_weight
      t.string :right_adrenal_pos_config_shape
      t.string :right_adrenal_gland_external_surface
      t.string :right_adrenal_gland_parenchyma_or_cut_surface
      t.string :right_adrenal_cortex
      t.string :right_adrenal_fetal_cortex
      t.string :right_adrenal_medulla
      t.text :right_adrenal_other
      t.integer :left_adrenal_gland_weight
      t.string :left_adrenal_pos_config_shape
      t.string :left_adrenal_gland_external_surface
      t.string :left_adrenal_gland_parenchyma_or_cut_surface
      t.string :left_adrenal_cortex
      t.string :left_adrenal_fetal_cortex
      t.string :left_adrenal_medulla
      t.text :left_adrenal_other
      t.integer :thyroid_weight
      t.string :thyroid_pos_config_shape
      t.string :thyroid_external_surface
      t.string :thyroid_parenchyma_or_cut_surface
      t.text :thyroid_other
      t.integer :pituitary_weight
      t.string :pituitary_pos_config_shape
      t.string :pituitary_external_surface
      t.string :pituitary_parenchyma_or_cut_surface
      t.string :parathyroid_gland
      t.integer :weight
      t.string :thymus_pos_config_shape
      t.string :petechiae_on_external_surface
      t.string :thymus_parenchyma_or_cut_surface
      t.text :thymus_other
      t.integer :spleen_weight
      t.string :spleen_shape_position_configuration
      t.string :capsular_surface
      t.string :spleen_consistency
      t.string :spleen_parenchyma_or_cut_surface
      t.string :accessory_spleens
      t.text :spleen_other
      t.text :cervical
      t.text :axillary
      t.text :mediastinal
      t.text :hilar
      t.text :celiac_peripancreatic
      t.text :mesenteric
      t.text :periaortic
      t.text :iliac
      t.text :inguinal
      t.text :lymph_nodes_other
      t.string :hardness
      t.string :bone_anomalies
      t.string :marrow
      t.text :bones_other
      t.string :skeletal_muscle_color_consistency
      t.string :skeletal_muscle_size
      t.text :skeletal_muscle_other
      t.string :bones
      t.string :sutures_fontanelles
      t.string :skull_base
      t.string :sella
      t.string :petrous_pyramids_opened_and_cultured
      t.string :ears_removed
      t.integer :foramen_magnum_antero_posterior_dimension
      t.integer :foramen_magnum_antero_lateral_dimension
      t.text :cranium_other
      t.string :dura_falx_tentorium
      t.string :subdural_epidural
      t.string :venous_sinuses
      t.text :sinuses_other
      t.integer :brain_weight
      t.string :configuration_lobar_pattern
      t.string :brain_consistency
      t.string :pachymeninges
      t.string :blood_vessels
      t.string :cranial_nerves
      t.string :kernicterus
      t.string :extradural_space
      t.string :meninges
      t.string :cord_proper
      t.string :peripheral_nervous_system
      t.string :peritoneal_serosal_surfaces_specify
      t.string :peritoneal_cavity_organ_relations_specify
      t.string :retrroperitoneum_specify
      t.string :umbilical_vessels_specify
      t.string :pleural_serosal_surfaces_specify
      t.string :pleural_cavity_organ_relations_specify
      t.string :diaphragm_specify
      t.string :mediastinum_position_configuration_specify
      t.string :mediastinum_nodes_masses_specify
      t.string :serosal_sarfaces_specify
      t.string :heart_position_specify
      t.string :epicardium_specify
      t.string :heart_shape_specify
      t.string :heart_size_specify
      t.string :configuration_and_contents_specify
      t.string :atrial_situs_specify
      t.string :ventricular_situs_specify
      t.string :ventricular_septum_specify
      t.string :endocardium_specify
      t.string :myocardium_specify
      t.string :tricuspid_valve_specify
      t.string :pulmonic_valve_specify
      t.string :mitral_valve_specify
      t.string :aortic_valve_specify
      t.string :origins_of_aorta_and_pulmonary_artery_specify
      t.string :arch_configuartion_specify
      t.string :coronary_arteries_specify
      t.string :arch_branches_specify
      t.string :thoracic_and_abdominal_branches_specify
      t.string :intima_and_wall_specify
      t.string :pulmonary_arteries_specify
      t.string :venous_system_state_of_distension_specify
      t.string :epiglottis_specify
      t.string :larynx_trachea_configuration_position_specify
      t.string :vocal_cords_specify
      t.string :mucosal_surfaces_specify
      t.string :lobar_pattern_specify
      t.string :state_of_expansion_specify
      t.string :lungs_consistency_specify
      t.string :bronchial_tree_specify
      t.string :vessels_specify
      t.string :parenchyma_color_specify
      t.string :hilar_nodes_specify
      t.string :visceral_pleura_specify
      t.string :esophagus_size_position_configuration_specify
      t.string :esophagus_mucosa_and_wall_specify
      t.string :stomach_size_position_configuration_specify
      t.string :stomach_mucosa_and_wall_specify
      t.string :ampulla_specify
      t.string :small_intestine_size_position_configuration_specify
      t.string :small_intestine_rotation_specify
      t.string :small_intestine_mucosa_and_wall_specify
      t.string :small_intestine_state_of_distension_specify
      t.string :large_intestine_size_position_configuration_specify
      t.string :large_intestine_rotation_specify
      t.string :large_intestine_mucosa_and_wall_specify
      t.string :large_intestine_state_of_distension_specify
      t.string :configuration_specify
      t.string :liver_size_shape_specify
      t.string :liver_and_billiary_system_external_surface_specify
      t.string :cut_surface_specify
      t.string :gallbladder_specify
      t.string :bile_ducts_specify
      t.string :vessels_portal_vein_hepatic_artery_specify
      t.string :size_configuration_specify
      t.string :pancreas_parenchyma_or_cut_surface_specify
      t.string :ducts_specify
      t.string :right_kidney_configuration_position_specify
      t.string :right_kidney_external_surface_specify
      t.string :right_kidney_parenchyma_or_cut_surface_specify
      t.string :right_kidney_pelves_and_calyces_specify
      t.string :right_kidney_peripelvic_fat_and_lymph_nodes_specify
      t.string :right_kidney_renal_vessels_specify
      t.string :right_kidney_ureter_specify
      t.string :left_kidney_configuration_position_specify
      t.string :left_kidney_external_surface_specify
      t.string :left_kidney_parenchyma_or_cut_surface_specify
      t.string :left_kidney_pelves_and_calyces_specify
      t.string :left_kideny_peripelvic_fat_and_lymph_nodes_specify
      t.string :left_panel_renal_vessels_specify
      t.string :left_kidney_ureter_specify
      t.string :size_and_configuration_specify
      t.string :wall_and_mucosa_specify
      t.string :perivesical_tissue_specify
      t.string :urethra_specify
      t.string :prostate_specify
      t.string :epididymis_specify
      t.string :testes_specify
      t.string :vagina_specify
      t.string :uterus_specify
      t.string :right_fallopian_tubes_specify
      t.string :right_ovary_specify
      t.string :left_fallopian_tube_specify
      t.string :left_ovary_specify
      t.string :right_adrenal_pos_config_shape_specify
      t.string :right_adrenal_gland_external_surface_specify
      t.string :right_adrenal_gland_parenchyma_or_cut_surface_specify
      t.string :right_adrenal_cortex_specify
      t.string :right_adrenal_fetal_cortex_specify
      t.string :right_adrenal_medulla_specify
      t.string :left_adrenal_pos_config_shape_specify
      t.string :left_adrenal_gland_external_surface_specify
      t.string :left_adrenal_gland_parenchyma_or_cut_surface_specify
      t.string :left_adrenal_cortex_specify
      t.string :left_adrenal_fetal_cortex_specify
      t.string :left_adrenal_medulla_specify
      t.string :thyroid_pos_config_shape_specify
      t.string :thyroid_external_surface_specify
      t.string :thyroid_parenchyma_or_cut_surface_specify
      t.string :pituitary_pos_config_shape_specify
      t.string :pituitary_external_surface_specify
      t.string :pituitary_parenchyma_or_cut_surface_specify
      t.string :thymus_pos_config_shape_specify
      t.string :thymus_parenchyma_or_cut_surface_specify
      t.string :spleen_shape_position_configuration_specify
      t.string :capsular_surface_specify
      t.string :spleen_consistency_specify
      t.string :spleen_parenchyma_or_cut_surface_specify
      t.string :hardness_specify
      t.string :bone_anomalies_specify
      t.string :marrow_specify
      t.string :skeletal_muscle_color_consistency_specify
      t.string :skeletal_muscle_size_specify
      t.string :bones_specify
      t.string :sutures_fontanelles_specify
      t.string :skull_base_specify
      t.string :sella_specify
      t.string :dura_falx_tentorium_specify
      t.string :subdural_epidural_specify
      t.string :venous_sinuses_specify
      t.string :configuration_lobar_pattern_specify
      t.string :brain_consistency_specify
      t.string :pachymeninges_specify
      t.string :blood_vessels_specify
      t.string :cranial_nerves_specify
      t.string :kernicterus_specify
      t.string :extradural_space_specify
      t.string :meninges_specify
      t.string :cord_proper_specify
      t.string :pleural_cavities_amount_of_fluid_specify
      t.string :pericardial_sac_amount_of_fluid_specify
      t.string :atrial_septum_specify
      t.string :ductus_specify
      t.string :peritoneal_nature_of_fluid_specify
      t.string :pleural_nature_of_fluid_specify
      t.string :pericardial_sac_contents_specify
      t.string :bile_specify
      t.string :venous_system_anomalies_specify
      t.string :stones_specify
      t.string :bladder_contents_specify
      t.integer :accessory_spleens_number
      t.integer :mecekel_diverticulum_size
      t.string :pneumothorax_specify
      t.string :foreign_material_in_lumen_specify
      t.string :fixed_by_perfusion_specify
      t.string :genitourinary_anomalies_specify
      t.string :petrous_pyramids_opened_and_cultured_specify
      t.string :ears_removed_specify
      t.references :description, index: true, foreign_key: true

      t.timestamps null: false
    end
  end
end
